[build-system]
build-backend = "setuptools.build_meta"
requires = [ "setuptools>=62.4.0", "wheel" ]

[project]
authors = [ { email = "novak9@stolaf.edu", name = "Gordon Novak" } ]
classifiers = [
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Compilers",
  "Topic :: Text Processing :: Linguistic",
  "Typing :: Typed",
]
description = "A small low-overhead scripting language used in a custom game engine."
keywords = [ "incremental", "parsing", "tree-sitter", "gscript" ]
license.text = "MIT"
name = "tree-sitter-gscript"
readme = "README.md"
requires-python = ">=3.10"
version = "0.1.0"

[project.urls]
Funding = ""
Homepage = "https://github.com/gorddev/gscript-treesitter.git"

[project.optional-dependencies]
core = [ "tree-sitter~=0.24" ]

[tool.cibuildwheel]
build = "cp310-*"
build-frontend = "build"
