/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 23
#define LARGE_STATE_COUNT 15
#define SYMBOL_COUNT 36
#define ALIAS_COUNT 2
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_fn = 1,
  anon_sym_LPAREN = 2,
  anon_sym_COMMA = 3,
  anon_sym_RPAREN = 4,
  sym_comment = 5,
  anon_sym_true = 6,
  anon_sym_false = 7,
  anon_sym_null = 8,
  anon_sym_use = 9,
  aux_sym_import_token1 = 10,
  anon_sym_if = 11,
  anon_sym_elif = 12,
  anon_sym_else = 13,
  anon_sym_for = 14,
  anon_sym_while = 15,
  anon_sym_return = 16,
  sym_number = 17,
  sym_string = 18,
  sym_escape = 19,
  anon_sym_bool = 20,
  anon_sym_int = 21,
  anon_sym_uint = 22,
  anon_sym_float = 23,
  anon_sym_str = 24,
  sym_source_file = 25,
  sym__definition = 26,
  sym_function_definition = 27,
  sym_parameter_list = 28,
  sym_constant = 29,
  sym_import = 30,
  sym_keyword = 31,
  sym_identifier = 32,
  sym_type = 33,
  aux_sym_source_file_repeat1 = 34,
  aux_sym_parameter_list_repeat1 = 35,
  alias_sym_function_name = 36,
  alias_sym_module_name = 37,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_fn] = "fn",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [sym_comment] = "comment",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_null] = "null",
  [anon_sym_use] = "use",
  [aux_sym_import_token1] = "import_token1",
  [anon_sym_if] = "if",
  [anon_sym_elif] = "elif",
  [anon_sym_else] = "else",
  [anon_sym_for] = "for",
  [anon_sym_while] = "while",
  [anon_sym_return] = "return",
  [sym_number] = "number",
  [sym_string] = "string",
  [sym_escape] = "escape",
  [anon_sym_bool] = "bool",
  [anon_sym_int] = "int",
  [anon_sym_uint] = "uint",
  [anon_sym_float] = "float",
  [anon_sym_str] = "str",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_function_definition] = "function_definition",
  [sym_parameter_list] = "parameter_list",
  [sym_constant] = "constant",
  [sym_import] = "import",
  [sym_keyword] = "keyword",
  [sym_identifier] = "identifier",
  [sym_type] = "type",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [alias_sym_function_name] = "function_name",
  [alias_sym_module_name] = "module_name",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_comment] = sym_comment,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_null] = anon_sym_null,
  [anon_sym_use] = anon_sym_use,
  [aux_sym_import_token1] = aux_sym_import_token1,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_elif] = anon_sym_elif,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_return] = anon_sym_return,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [sym_escape] = sym_escape,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_uint] = anon_sym_uint,
  [anon_sym_float] = anon_sym_float,
  [anon_sym_str] = anon_sym_str,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_function_definition] = sym_function_definition,
  [sym_parameter_list] = sym_parameter_list,
  [sym_constant] = sym_constant,
  [sym_import] = sym_import,
  [sym_keyword] = sym_keyword,
  [sym_identifier] = sym_identifier,
  [sym_type] = sym_type,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [alias_sym_function_name] = alias_sym_function_name,
  [alias_sym_module_name] = alias_sym_module_name,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_null] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_use] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_import_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_escape] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_uint] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_float] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_str] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_constant] = {
    .visible = true,
    .named = true,
  },
  [sym_import] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_function_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_module_name] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = alias_sym_module_name,
  },
  [2] = {
    [1] = alias_sym_function_name,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym_identifier, 2,
    sym_identifier,
    alias_sym_function_name,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      ADVANCE_MAP(
        '"', 1,
        '#', 10,
        '(', 7,
        ')', 9,
        ',', 8,
        '\\', 3,
        'b', 38,
        'e', 32,
        'f', 15,
        'i', 23,
        'n', 50,
        'r', 22,
        's', 49,
        't', 42,
        'u', 26,
        'w', 25,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == ')') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 3:
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(63);
      END_STATE();
    case 4:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_fn);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_null);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_use);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'a') ADVANCE(29);
      if (lookahead == 'l') ADVANCE(37);
      if (lookahead == 'n') ADVANCE(6);
      if (lookahead == 'o') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'a') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'e') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'e') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'e') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'e') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'e') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'e') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'f') ADVANCE(54);
      if (lookahead == 'n') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'f') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'h') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'i') ADVANCE(36);
      if (lookahead == 's') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'i') ADVANCE(24);
      if (lookahead == 's') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'i') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'l') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'l') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'l') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'l') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'l') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'l') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'n') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'n') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'o') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'o') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'o') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'r') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'r') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'r') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'r') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 's') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 't') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 't') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 't') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 't') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 't') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'u') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'u') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'u') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_elif);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_else);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_for);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_while);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_return);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_escape);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_bool);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_int);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_uint);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_float);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_str);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_null] = ACTIONS(1),
    [anon_sym_use] = ACTIONS(1),
    [aux_sym_import_token1] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_elif] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_escape] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_uint] = ACTIONS(1),
    [anon_sym_float] = ACTIONS(1),
    [anon_sym_str] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(22),
    [sym__definition] = STATE(2),
    [sym_function_definition] = STATE(2),
    [sym_constant] = STATE(2),
    [sym_import] = STATE(2),
    [sym_keyword] = STATE(2),
    [sym_identifier] = STATE(2),
    [sym_type] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_fn] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
    [anon_sym_true] = ACTIONS(9),
    [anon_sym_false] = ACTIONS(9),
    [anon_sym_null] = ACTIONS(9),
    [anon_sym_use] = ACTIONS(11),
    [aux_sym_import_token1] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_elif] = ACTIONS(15),
    [anon_sym_else] = ACTIONS(15),
    [anon_sym_for] = ACTIONS(15),
    [anon_sym_while] = ACTIONS(15),
    [anon_sym_return] = ACTIONS(15),
    [sym_number] = ACTIONS(7),
    [sym_string] = ACTIONS(7),
    [sym_escape] = ACTIONS(7),
    [anon_sym_bool] = ACTIONS(17),
    [anon_sym_int] = ACTIONS(17),
    [anon_sym_uint] = ACTIONS(17),
    [anon_sym_float] = ACTIONS(17),
    [anon_sym_str] = ACTIONS(17),
  },
  [STATE(2)] = {
    [sym__definition] = STATE(3),
    [sym_function_definition] = STATE(3),
    [sym_constant] = STATE(3),
    [sym_import] = STATE(3),
    [sym_keyword] = STATE(3),
    [sym_identifier] = STATE(3),
    [sym_type] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(5),
    [sym_comment] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(9),
    [anon_sym_false] = ACTIONS(9),
    [anon_sym_null] = ACTIONS(9),
    [anon_sym_use] = ACTIONS(11),
    [aux_sym_import_token1] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_elif] = ACTIONS(15),
    [anon_sym_else] = ACTIONS(15),
    [anon_sym_for] = ACTIONS(15),
    [anon_sym_while] = ACTIONS(15),
    [anon_sym_return] = ACTIONS(15),
    [sym_number] = ACTIONS(21),
    [sym_string] = ACTIONS(21),
    [sym_escape] = ACTIONS(21),
    [anon_sym_bool] = ACTIONS(17),
    [anon_sym_int] = ACTIONS(17),
    [anon_sym_uint] = ACTIONS(17),
    [anon_sym_float] = ACTIONS(17),
    [anon_sym_str] = ACTIONS(17),
  },
  [STATE(3)] = {
    [sym__definition] = STATE(3),
    [sym_function_definition] = STATE(3),
    [sym_constant] = STATE(3),
    [sym_import] = STATE(3),
    [sym_keyword] = STATE(3),
    [sym_identifier] = STATE(3),
    [sym_type] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(23),
    [anon_sym_fn] = ACTIONS(25),
    [sym_comment] = ACTIONS(28),
    [anon_sym_true] = ACTIONS(31),
    [anon_sym_false] = ACTIONS(31),
    [anon_sym_null] = ACTIONS(31),
    [anon_sym_use] = ACTIONS(34),
    [aux_sym_import_token1] = ACTIONS(37),
    [anon_sym_if] = ACTIONS(40),
    [anon_sym_elif] = ACTIONS(40),
    [anon_sym_else] = ACTIONS(40),
    [anon_sym_for] = ACTIONS(40),
    [anon_sym_while] = ACTIONS(40),
    [anon_sym_return] = ACTIONS(40),
    [sym_number] = ACTIONS(28),
    [sym_string] = ACTIONS(28),
    [sym_escape] = ACTIONS(28),
    [anon_sym_bool] = ACTIONS(43),
    [anon_sym_int] = ACTIONS(43),
    [anon_sym_uint] = ACTIONS(43),
    [anon_sym_float] = ACTIONS(43),
    [anon_sym_str] = ACTIONS(43),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(46),
    [anon_sym_fn] = ACTIONS(48),
    [anon_sym_LPAREN] = ACTIONS(46),
    [anon_sym_COMMA] = ACTIONS(46),
    [anon_sym_RPAREN] = ACTIONS(46),
    [sym_comment] = ACTIONS(46),
    [anon_sym_true] = ACTIONS(48),
    [anon_sym_false] = ACTIONS(48),
    [anon_sym_null] = ACTIONS(48),
    [anon_sym_use] = ACTIONS(48),
    [aux_sym_import_token1] = ACTIONS(48),
    [anon_sym_if] = ACTIONS(48),
    [anon_sym_elif] = ACTIONS(48),
    [anon_sym_else] = ACTIONS(48),
    [anon_sym_for] = ACTIONS(48),
    [anon_sym_while] = ACTIONS(48),
    [anon_sym_return] = ACTIONS(48),
    [sym_number] = ACTIONS(46),
    [sym_string] = ACTIONS(46),
    [sym_escape] = ACTIONS(46),
    [anon_sym_bool] = ACTIONS(48),
    [anon_sym_int] = ACTIONS(48),
    [anon_sym_uint] = ACTIONS(48),
    [anon_sym_float] = ACTIONS(48),
    [anon_sym_str] = ACTIONS(48),
  },
  [STATE(5)] = {
    [sym_identifier] = STATE(19),
    [ts_builtin_sym_end] = ACTIONS(50),
    [anon_sym_fn] = ACTIONS(52),
    [sym_comment] = ACTIONS(50),
    [anon_sym_true] = ACTIONS(52),
    [anon_sym_false] = ACTIONS(52),
    [anon_sym_null] = ACTIONS(52),
    [anon_sym_use] = ACTIONS(52),
    [aux_sym_import_token1] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(52),
    [anon_sym_elif] = ACTIONS(52),
    [anon_sym_else] = ACTIONS(52),
    [anon_sym_for] = ACTIONS(52),
    [anon_sym_while] = ACTIONS(52),
    [anon_sym_return] = ACTIONS(52),
    [sym_number] = ACTIONS(50),
    [sym_string] = ACTIONS(50),
    [sym_escape] = ACTIONS(50),
    [anon_sym_bool] = ACTIONS(52),
    [anon_sym_int] = ACTIONS(52),
    [anon_sym_uint] = ACTIONS(52),
    [anon_sym_float] = ACTIONS(52),
    [anon_sym_str] = ACTIONS(52),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(54),
    [anon_sym_fn] = ACTIONS(56),
    [sym_comment] = ACTIONS(54),
    [anon_sym_true] = ACTIONS(56),
    [anon_sym_false] = ACTIONS(56),
    [anon_sym_null] = ACTIONS(56),
    [anon_sym_use] = ACTIONS(56),
    [aux_sym_import_token1] = ACTIONS(56),
    [anon_sym_if] = ACTIONS(56),
    [anon_sym_elif] = ACTIONS(56),
    [anon_sym_else] = ACTIONS(56),
    [anon_sym_for] = ACTIONS(56),
    [anon_sym_while] = ACTIONS(56),
    [anon_sym_return] = ACTIONS(56),
    [sym_number] = ACTIONS(54),
    [sym_string] = ACTIONS(54),
    [sym_escape] = ACTIONS(54),
    [anon_sym_bool] = ACTIONS(56),
    [anon_sym_int] = ACTIONS(56),
    [anon_sym_uint] = ACTIONS(56),
    [anon_sym_float] = ACTIONS(56),
    [anon_sym_str] = ACTIONS(56),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(50),
    [anon_sym_fn] = ACTIONS(52),
    [sym_comment] = ACTIONS(50),
    [anon_sym_true] = ACTIONS(52),
    [anon_sym_false] = ACTIONS(52),
    [anon_sym_null] = ACTIONS(52),
    [anon_sym_use] = ACTIONS(52),
    [aux_sym_import_token1] = ACTIONS(58),
    [anon_sym_if] = ACTIONS(52),
    [anon_sym_elif] = ACTIONS(52),
    [anon_sym_else] = ACTIONS(52),
    [anon_sym_for] = ACTIONS(52),
    [anon_sym_while] = ACTIONS(52),
    [anon_sym_return] = ACTIONS(52),
    [sym_number] = ACTIONS(50),
    [sym_string] = ACTIONS(50),
    [sym_escape] = ACTIONS(50),
    [anon_sym_bool] = ACTIONS(52),
    [anon_sym_int] = ACTIONS(52),
    [anon_sym_uint] = ACTIONS(52),
    [anon_sym_float] = ACTIONS(52),
    [anon_sym_str] = ACTIONS(52),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(50),
    [anon_sym_fn] = ACTIONS(52),
    [sym_comment] = ACTIONS(50),
    [anon_sym_true] = ACTIONS(52),
    [anon_sym_false] = ACTIONS(52),
    [anon_sym_null] = ACTIONS(52),
    [anon_sym_use] = ACTIONS(52),
    [aux_sym_import_token1] = ACTIONS(52),
    [anon_sym_if] = ACTIONS(52),
    [anon_sym_elif] = ACTIONS(52),
    [anon_sym_else] = ACTIONS(52),
    [anon_sym_for] = ACTIONS(52),
    [anon_sym_while] = ACTIONS(52),
    [anon_sym_return] = ACTIONS(52),
    [sym_number] = ACTIONS(50),
    [sym_string] = ACTIONS(50),
    [sym_escape] = ACTIONS(50),
    [anon_sym_bool] = ACTIONS(52),
    [anon_sym_int] = ACTIONS(52),
    [anon_sym_uint] = ACTIONS(52),
    [anon_sym_float] = ACTIONS(52),
    [anon_sym_str] = ACTIONS(52),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(61),
    [anon_sym_fn] = ACTIONS(63),
    [sym_comment] = ACTIONS(61),
    [anon_sym_true] = ACTIONS(63),
    [anon_sym_false] = ACTIONS(63),
    [anon_sym_null] = ACTIONS(63),
    [anon_sym_use] = ACTIONS(63),
    [aux_sym_import_token1] = ACTIONS(63),
    [anon_sym_if] = ACTIONS(63),
    [anon_sym_elif] = ACTIONS(63),
    [anon_sym_else] = ACTIONS(63),
    [anon_sym_for] = ACTIONS(63),
    [anon_sym_while] = ACTIONS(63),
    [anon_sym_return] = ACTIONS(63),
    [sym_number] = ACTIONS(61),
    [sym_string] = ACTIONS(61),
    [sym_escape] = ACTIONS(61),
    [anon_sym_bool] = ACTIONS(63),
    [anon_sym_int] = ACTIONS(63),
    [anon_sym_uint] = ACTIONS(63),
    [anon_sym_float] = ACTIONS(63),
    [anon_sym_str] = ACTIONS(63),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(65),
    [anon_sym_fn] = ACTIONS(67),
    [sym_comment] = ACTIONS(65),
    [anon_sym_true] = ACTIONS(67),
    [anon_sym_false] = ACTIONS(67),
    [anon_sym_null] = ACTIONS(67),
    [anon_sym_use] = ACTIONS(67),
    [aux_sym_import_token1] = ACTIONS(67),
    [anon_sym_if] = ACTIONS(67),
    [anon_sym_elif] = ACTIONS(67),
    [anon_sym_else] = ACTIONS(67),
    [anon_sym_for] = ACTIONS(67),
    [anon_sym_while] = ACTIONS(67),
    [anon_sym_return] = ACTIONS(67),
    [sym_number] = ACTIONS(65),
    [sym_string] = ACTIONS(65),
    [sym_escape] = ACTIONS(65),
    [anon_sym_bool] = ACTIONS(67),
    [anon_sym_int] = ACTIONS(67),
    [anon_sym_uint] = ACTIONS(67),
    [anon_sym_float] = ACTIONS(67),
    [anon_sym_str] = ACTIONS(67),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(69),
    [anon_sym_fn] = ACTIONS(71),
    [sym_comment] = ACTIONS(69),
    [anon_sym_true] = ACTIONS(71),
    [anon_sym_false] = ACTIONS(71),
    [anon_sym_null] = ACTIONS(71),
    [anon_sym_use] = ACTIONS(71),
    [aux_sym_import_token1] = ACTIONS(71),
    [anon_sym_if] = ACTIONS(71),
    [anon_sym_elif] = ACTIONS(71),
    [anon_sym_else] = ACTIONS(71),
    [anon_sym_for] = ACTIONS(71),
    [anon_sym_while] = ACTIONS(71),
    [anon_sym_return] = ACTIONS(71),
    [sym_number] = ACTIONS(69),
    [sym_string] = ACTIONS(69),
    [sym_escape] = ACTIONS(69),
    [anon_sym_bool] = ACTIONS(71),
    [anon_sym_int] = ACTIONS(71),
    [anon_sym_uint] = ACTIONS(71),
    [anon_sym_float] = ACTIONS(71),
    [anon_sym_str] = ACTIONS(71),
  },
  [STATE(12)] = {
    [ts_builtin_sym_end] = ACTIONS(73),
    [anon_sym_fn] = ACTIONS(75),
    [sym_comment] = ACTIONS(73),
    [anon_sym_true] = ACTIONS(75),
    [anon_sym_false] = ACTIONS(75),
    [anon_sym_null] = ACTIONS(75),
    [anon_sym_use] = ACTIONS(75),
    [aux_sym_import_token1] = ACTIONS(75),
    [anon_sym_if] = ACTIONS(75),
    [anon_sym_elif] = ACTIONS(75),
    [anon_sym_else] = ACTIONS(75),
    [anon_sym_for] = ACTIONS(75),
    [anon_sym_while] = ACTIONS(75),
    [anon_sym_return] = ACTIONS(75),
    [sym_number] = ACTIONS(73),
    [sym_string] = ACTIONS(73),
    [sym_escape] = ACTIONS(73),
    [anon_sym_bool] = ACTIONS(75),
    [anon_sym_int] = ACTIONS(75),
    [anon_sym_uint] = ACTIONS(75),
    [anon_sym_float] = ACTIONS(75),
    [anon_sym_str] = ACTIONS(75),
  },
  [STATE(13)] = {
    [ts_builtin_sym_end] = ACTIONS(77),
    [anon_sym_fn] = ACTIONS(79),
    [sym_comment] = ACTIONS(77),
    [anon_sym_true] = ACTIONS(79),
    [anon_sym_false] = ACTIONS(79),
    [anon_sym_null] = ACTIONS(79),
    [anon_sym_use] = ACTIONS(79),
    [aux_sym_import_token1] = ACTIONS(79),
    [anon_sym_if] = ACTIONS(79),
    [anon_sym_elif] = ACTIONS(79),
    [anon_sym_else] = ACTIONS(79),
    [anon_sym_for] = ACTIONS(79),
    [anon_sym_while] = ACTIONS(79),
    [anon_sym_return] = ACTIONS(79),
    [sym_number] = ACTIONS(77),
    [sym_string] = ACTIONS(77),
    [sym_escape] = ACTIONS(77),
    [anon_sym_bool] = ACTIONS(79),
    [anon_sym_int] = ACTIONS(79),
    [anon_sym_uint] = ACTIONS(79),
    [anon_sym_float] = ACTIONS(79),
    [anon_sym_str] = ACTIONS(79),
  },
  [STATE(14)] = {
    [ts_builtin_sym_end] = ACTIONS(81),
    [anon_sym_fn] = ACTIONS(83),
    [sym_comment] = ACTIONS(81),
    [anon_sym_true] = ACTIONS(83),
    [anon_sym_false] = ACTIONS(83),
    [anon_sym_null] = ACTIONS(83),
    [anon_sym_use] = ACTIONS(83),
    [aux_sym_import_token1] = ACTIONS(83),
    [anon_sym_if] = ACTIONS(83),
    [anon_sym_elif] = ACTIONS(83),
    [anon_sym_else] = ACTIONS(83),
    [anon_sym_for] = ACTIONS(83),
    [anon_sym_while] = ACTIONS(83),
    [anon_sym_return] = ACTIONS(83),
    [sym_number] = ACTIONS(81),
    [sym_string] = ACTIONS(81),
    [sym_escape] = ACTIONS(81),
    [anon_sym_bool] = ACTIONS(83),
    [anon_sym_int] = ACTIONS(83),
    [anon_sym_uint] = ACTIONS(83),
    [anon_sym_float] = ACTIONS(83),
    [anon_sym_str] = ACTIONS(83),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(85), 1,
      anon_sym_RPAREN,
    ACTIONS(87), 1,
      aux_sym_import_token1,
    STATE(17), 1,
      sym_identifier,
  [10] = 3,
    ACTIONS(89), 1,
      anon_sym_COMMA,
    ACTIONS(91), 1,
      anon_sym_RPAREN,
    STATE(18), 1,
      aux_sym_parameter_list_repeat1,
  [20] = 3,
    ACTIONS(89), 1,
      anon_sym_COMMA,
    ACTIONS(93), 1,
      anon_sym_RPAREN,
    STATE(16), 1,
      aux_sym_parameter_list_repeat1,
  [30] = 3,
    ACTIONS(95), 1,
      anon_sym_COMMA,
    ACTIONS(98), 1,
      anon_sym_RPAREN,
    STATE(18), 1,
      aux_sym_parameter_list_repeat1,
  [40] = 2,
    ACTIONS(100), 1,
      anon_sym_LPAREN,
    STATE(12), 1,
      sym_parameter_list,
  [47] = 2,
    ACTIONS(87), 1,
      aux_sym_import_token1,
    STATE(21), 1,
      sym_identifier,
  [54] = 1,
    ACTIONS(98), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [59] = 1,
    ACTIONS(102), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(15)] = 0,
  [SMALL_STATE(16)] = 10,
  [SMALL_STATE(17)] = 20,
  [SMALL_STATE(18)] = 30,
  [SMALL_STATE(19)] = 40,
  [SMALL_STATE(20)] = 47,
  [SMALL_STATE(21)] = 54,
  [SMALL_STATE(22)] = 59,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant, 1, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constant, 1, 0, 0),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_keyword, 1, 0, 0), SHIFT(10),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 2, 0, 1),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 2, 0, 1),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 3, 0, 2),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 3, 0, 2),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 4, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 4, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [102] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gscript(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "gscript",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
