/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 29
#define LARGE_STATE_COUNT 16
#define SYMBOL_COUNT 42
#define ALIAS_COUNT 2
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_if = 1,
  anon_sym_elif = 2,
  anon_sym_else = 3,
  anon_sym_for = 4,
  anon_sym_while = 5,
  anon_sym_return = 6,
  anon_sym_as = 7,
  sym_comment = 8,
  anon_sym_true = 9,
  anon_sym_false = 10,
  anon_sym_null = 11,
  anon_sym_bool = 12,
  anon_sym_int = 13,
  anon_sym_uint = 14,
  anon_sym_float = 15,
  anon_sym_str = 16,
  anon_sym_use = 17,
  aux_sym_import_token1 = 18,
  anon_sym_fn = 19,
  anon_sym_LPAREN = 20,
  anon_sym_COMMA = 21,
  anon_sym_RPAREN = 22,
  sym_number = 23,
  anon_sym_DQUOTE = 24,
  aux_sym_string_token1 = 25,
  sym_escape = 26,
  sym_source_file = 27,
  sym__definition = 28,
  sym__expression = 29,
  sym_keyword = 30,
  sym_constant = 31,
  sym_type = 32,
  sym_special_type = 33,
  sym_import = 34,
  sym_function_definition = 35,
  sym_parameter_list = 36,
  sym_string = 37,
  sym_identifier = 38,
  aux_sym_source_file_repeat1 = 39,
  aux_sym_parameter_list_repeat1 = 40,
  aux_sym_string_repeat1 = 41,
  alias_sym_function_name = 42,
  alias_sym_module_name = 43,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_if] = "if",
  [anon_sym_elif] = "elif",
  [anon_sym_else] = "else",
  [anon_sym_for] = "for",
  [anon_sym_while] = "while",
  [anon_sym_return] = "return",
  [anon_sym_as] = "as",
  [sym_comment] = "comment",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_null] = "null",
  [anon_sym_bool] = "bool",
  [anon_sym_int] = "int",
  [anon_sym_uint] = "uint",
  [anon_sym_float] = "float",
  [anon_sym_str] = "str",
  [anon_sym_use] = "use",
  [aux_sym_import_token1] = "import_token1",
  [anon_sym_fn] = "fn",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_escape] = "escape",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym__expression] = "_expression",
  [sym_keyword] = "keyword",
  [sym_constant] = "constant",
  [sym_type] = "type",
  [sym_special_type] = "special_type",
  [sym_import] = "import",
  [sym_function_definition] = "function_definition",
  [sym_parameter_list] = "parameter_list",
  [sym_string] = "string",
  [sym_identifier] = "identifier",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [alias_sym_function_name] = "function_name",
  [alias_sym_module_name] = "module_name",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_elif] = anon_sym_elif,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_as] = anon_sym_as,
  [sym_comment] = sym_comment,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_null] = anon_sym_null,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_uint] = anon_sym_uint,
  [anon_sym_float] = anon_sym_float,
  [anon_sym_str] = anon_sym_str,
  [anon_sym_use] = anon_sym_use,
  [aux_sym_import_token1] = aux_sym_import_token1,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_escape] = sym_escape,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym__expression] = sym__expression,
  [sym_keyword] = sym_keyword,
  [sym_constant] = sym_constant,
  [sym_type] = sym_type,
  [sym_special_type] = sym_special_type,
  [sym_import] = sym_import,
  [sym_function_definition] = sym_function_definition,
  [sym_parameter_list] = sym_parameter_list,
  [sym_string] = sym_string,
  [sym_identifier] = sym_identifier,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [alias_sym_function_name] = alias_sym_function_name,
  [alias_sym_module_name] = alias_sym_module_name,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_null] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_uint] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_float] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_str] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_use] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_import_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_constant] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_special_type] = {
    .visible = true,
    .named = true,
  },
  [sym_import] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_function_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_module_name] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = alias_sym_module_name,
  },
  [2] = {
    [1] = alias_sym_function_name,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym_identifier, 2,
    sym_identifier,
    alias_sym_function_name,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      ADVANCE_MAP(
        '"', 69,
        '#', 13,
        '(', 64,
        ')', 66,
        ',', 65,
        '\\', 3,
        'a', 52,
        'b', 46,
        'e', 40,
        'f', 23,
        'i', 31,
        'n', 59,
        'r', 30,
        's', 58,
        't', 50,
        'u', 34,
        'w', 33,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(67);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('c' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '"') ADVANCE(69);
      if (lookahead == '\\') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(71);
      if (lookahead != 0) ADVANCE(70);
      END_STATE();
    case 2:
      if (lookahead == ')') ADVANCE(66);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 3:
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(72);
      END_STATE();
    case 4:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_elif);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_else);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_for);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_while);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_return);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_as);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_null);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_bool);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_int);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_uint);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_float);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_str);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_use);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'a') ADVANCE(39);
      if (lookahead == 'l') ADVANCE(45);
      if (lookahead == 'n') ADVANCE(63);
      if (lookahead == 'o') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'a') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'e') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'e') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'e') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'e') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'e') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'e') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'f') ADVANCE(6);
      if (lookahead == 'n') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'f') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'h') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'i') ADVANCE(44);
      if (lookahead == 's') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'i') ADVANCE(32);
      if (lookahead == 's') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'i') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'l') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'l') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'l') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'l') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'l') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'l') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'n') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'n') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'o') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'o') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'o') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'r') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'r') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'r') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'r') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 's') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 's') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 't') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 't') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 't') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 't') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 't') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'u') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'u') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'u') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_fn);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(71);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(70);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_escape);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_elif] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_null] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_uint] = ACTIONS(1),
    [anon_sym_float] = ACTIONS(1),
    [anon_sym_str] = ACTIONS(1),
    [anon_sym_use] = ACTIONS(1),
    [aux_sym_import_token1] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(28),
    [sym__definition] = STATE(2),
    [sym__expression] = STATE(2),
    [sym_keyword] = STATE(2),
    [sym_constant] = STATE(2),
    [sym_type] = STATE(2),
    [sym_special_type] = STATE(2),
    [sym_import] = STATE(2),
    [sym_function_definition] = STATE(2),
    [sym_string] = STATE(2),
    [sym_identifier] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_if] = ACTIONS(5),
    [anon_sym_elif] = ACTIONS(5),
    [anon_sym_else] = ACTIONS(5),
    [anon_sym_for] = ACTIONS(5),
    [anon_sym_while] = ACTIONS(5),
    [anon_sym_return] = ACTIONS(5),
    [anon_sym_as] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
    [anon_sym_true] = ACTIONS(9),
    [anon_sym_false] = ACTIONS(9),
    [anon_sym_null] = ACTIONS(9),
    [anon_sym_bool] = ACTIONS(11),
    [anon_sym_int] = ACTIONS(11),
    [anon_sym_uint] = ACTIONS(11),
    [anon_sym_float] = ACTIONS(11),
    [anon_sym_str] = ACTIONS(13),
    [anon_sym_use] = ACTIONS(15),
    [aux_sym_import_token1] = ACTIONS(17),
    [anon_sym_fn] = ACTIONS(19),
    [sym_number] = ACTIONS(7),
    [anon_sym_DQUOTE] = ACTIONS(21),
  },
  [STATE(2)] = {
    [sym__definition] = STATE(3),
    [sym__expression] = STATE(3),
    [sym_keyword] = STATE(3),
    [sym_constant] = STATE(3),
    [sym_type] = STATE(3),
    [sym_special_type] = STATE(3),
    [sym_import] = STATE(3),
    [sym_function_definition] = STATE(3),
    [sym_string] = STATE(3),
    [sym_identifier] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(23),
    [anon_sym_if] = ACTIONS(5),
    [anon_sym_elif] = ACTIONS(5),
    [anon_sym_else] = ACTIONS(5),
    [anon_sym_for] = ACTIONS(5),
    [anon_sym_while] = ACTIONS(5),
    [anon_sym_return] = ACTIONS(5),
    [anon_sym_as] = ACTIONS(5),
    [sym_comment] = ACTIONS(25),
    [anon_sym_true] = ACTIONS(9),
    [anon_sym_false] = ACTIONS(9),
    [anon_sym_null] = ACTIONS(9),
    [anon_sym_bool] = ACTIONS(11),
    [anon_sym_int] = ACTIONS(11),
    [anon_sym_uint] = ACTIONS(11),
    [anon_sym_float] = ACTIONS(11),
    [anon_sym_str] = ACTIONS(13),
    [anon_sym_use] = ACTIONS(15),
    [aux_sym_import_token1] = ACTIONS(17),
    [anon_sym_fn] = ACTIONS(19),
    [sym_number] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(21),
  },
  [STATE(3)] = {
    [sym__definition] = STATE(3),
    [sym__expression] = STATE(3),
    [sym_keyword] = STATE(3),
    [sym_constant] = STATE(3),
    [sym_type] = STATE(3),
    [sym_special_type] = STATE(3),
    [sym_import] = STATE(3),
    [sym_function_definition] = STATE(3),
    [sym_string] = STATE(3),
    [sym_identifier] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(27),
    [anon_sym_if] = ACTIONS(29),
    [anon_sym_elif] = ACTIONS(29),
    [anon_sym_else] = ACTIONS(29),
    [anon_sym_for] = ACTIONS(29),
    [anon_sym_while] = ACTIONS(29),
    [anon_sym_return] = ACTIONS(29),
    [anon_sym_as] = ACTIONS(29),
    [sym_comment] = ACTIONS(32),
    [anon_sym_true] = ACTIONS(35),
    [anon_sym_false] = ACTIONS(35),
    [anon_sym_null] = ACTIONS(35),
    [anon_sym_bool] = ACTIONS(38),
    [anon_sym_int] = ACTIONS(38),
    [anon_sym_uint] = ACTIONS(38),
    [anon_sym_float] = ACTIONS(38),
    [anon_sym_str] = ACTIONS(41),
    [anon_sym_use] = ACTIONS(44),
    [aux_sym_import_token1] = ACTIONS(47),
    [anon_sym_fn] = ACTIONS(50),
    [sym_number] = ACTIONS(32),
    [anon_sym_DQUOTE] = ACTIONS(53),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(56),
    [anon_sym_if] = ACTIONS(58),
    [anon_sym_elif] = ACTIONS(58),
    [anon_sym_else] = ACTIONS(58),
    [anon_sym_for] = ACTIONS(58),
    [anon_sym_while] = ACTIONS(58),
    [anon_sym_return] = ACTIONS(58),
    [anon_sym_as] = ACTIONS(58),
    [sym_comment] = ACTIONS(56),
    [anon_sym_true] = ACTIONS(58),
    [anon_sym_false] = ACTIONS(58),
    [anon_sym_null] = ACTIONS(58),
    [anon_sym_bool] = ACTIONS(58),
    [anon_sym_int] = ACTIONS(58),
    [anon_sym_uint] = ACTIONS(58),
    [anon_sym_float] = ACTIONS(58),
    [anon_sym_str] = ACTIONS(58),
    [anon_sym_use] = ACTIONS(58),
    [aux_sym_import_token1] = ACTIONS(58),
    [anon_sym_fn] = ACTIONS(58),
    [anon_sym_LPAREN] = ACTIONS(56),
    [anon_sym_COMMA] = ACTIONS(56),
    [anon_sym_RPAREN] = ACTIONS(56),
    [sym_number] = ACTIONS(56),
    [anon_sym_DQUOTE] = ACTIONS(56),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(60),
    [anon_sym_if] = ACTIONS(62),
    [anon_sym_elif] = ACTIONS(62),
    [anon_sym_else] = ACTIONS(62),
    [anon_sym_for] = ACTIONS(62),
    [anon_sym_while] = ACTIONS(62),
    [anon_sym_return] = ACTIONS(62),
    [anon_sym_as] = ACTIONS(62),
    [sym_comment] = ACTIONS(60),
    [anon_sym_true] = ACTIONS(62),
    [anon_sym_false] = ACTIONS(62),
    [anon_sym_null] = ACTIONS(62),
    [anon_sym_bool] = ACTIONS(62),
    [anon_sym_int] = ACTIONS(62),
    [anon_sym_uint] = ACTIONS(62),
    [anon_sym_float] = ACTIONS(62),
    [anon_sym_str] = ACTIONS(62),
    [anon_sym_use] = ACTIONS(62),
    [aux_sym_import_token1] = ACTIONS(62),
    [anon_sym_fn] = ACTIONS(62),
    [sym_number] = ACTIONS(60),
    [anon_sym_DQUOTE] = ACTIONS(60),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(64),
    [anon_sym_if] = ACTIONS(66),
    [anon_sym_elif] = ACTIONS(66),
    [anon_sym_else] = ACTIONS(66),
    [anon_sym_for] = ACTIONS(66),
    [anon_sym_while] = ACTIONS(66),
    [anon_sym_return] = ACTIONS(66),
    [anon_sym_as] = ACTIONS(66),
    [sym_comment] = ACTIONS(64),
    [anon_sym_true] = ACTIONS(66),
    [anon_sym_false] = ACTIONS(66),
    [anon_sym_null] = ACTIONS(66),
    [anon_sym_bool] = ACTIONS(66),
    [anon_sym_int] = ACTIONS(66),
    [anon_sym_uint] = ACTIONS(66),
    [anon_sym_float] = ACTIONS(66),
    [anon_sym_str] = ACTIONS(66),
    [anon_sym_use] = ACTIONS(66),
    [aux_sym_import_token1] = ACTIONS(66),
    [anon_sym_fn] = ACTIONS(66),
    [sym_number] = ACTIONS(64),
    [anon_sym_DQUOTE] = ACTIONS(64),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(68),
    [anon_sym_if] = ACTIONS(70),
    [anon_sym_elif] = ACTIONS(70),
    [anon_sym_else] = ACTIONS(70),
    [anon_sym_for] = ACTIONS(70),
    [anon_sym_while] = ACTIONS(70),
    [anon_sym_return] = ACTIONS(70),
    [anon_sym_as] = ACTIONS(70),
    [sym_comment] = ACTIONS(68),
    [anon_sym_true] = ACTIONS(70),
    [anon_sym_false] = ACTIONS(70),
    [anon_sym_null] = ACTIONS(70),
    [anon_sym_bool] = ACTIONS(70),
    [anon_sym_int] = ACTIONS(70),
    [anon_sym_uint] = ACTIONS(70),
    [anon_sym_float] = ACTIONS(70),
    [anon_sym_str] = ACTIONS(70),
    [anon_sym_use] = ACTIONS(70),
    [aux_sym_import_token1] = ACTIONS(70),
    [anon_sym_fn] = ACTIONS(70),
    [sym_number] = ACTIONS(68),
    [anon_sym_DQUOTE] = ACTIONS(68),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(72),
    [anon_sym_if] = ACTIONS(74),
    [anon_sym_elif] = ACTIONS(74),
    [anon_sym_else] = ACTIONS(74),
    [anon_sym_for] = ACTIONS(74),
    [anon_sym_while] = ACTIONS(74),
    [anon_sym_return] = ACTIONS(74),
    [anon_sym_as] = ACTIONS(74),
    [sym_comment] = ACTIONS(72),
    [anon_sym_true] = ACTIONS(74),
    [anon_sym_false] = ACTIONS(74),
    [anon_sym_null] = ACTIONS(74),
    [anon_sym_bool] = ACTIONS(74),
    [anon_sym_int] = ACTIONS(74),
    [anon_sym_uint] = ACTIONS(74),
    [anon_sym_float] = ACTIONS(74),
    [anon_sym_str] = ACTIONS(74),
    [anon_sym_use] = ACTIONS(74),
    [aux_sym_import_token1] = ACTIONS(74),
    [anon_sym_fn] = ACTIONS(74),
    [sym_number] = ACTIONS(72),
    [anon_sym_DQUOTE] = ACTIONS(72),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(76),
    [anon_sym_if] = ACTIONS(78),
    [anon_sym_elif] = ACTIONS(78),
    [anon_sym_else] = ACTIONS(78),
    [anon_sym_for] = ACTIONS(78),
    [anon_sym_while] = ACTIONS(78),
    [anon_sym_return] = ACTIONS(78),
    [anon_sym_as] = ACTIONS(78),
    [sym_comment] = ACTIONS(76),
    [anon_sym_true] = ACTIONS(78),
    [anon_sym_false] = ACTIONS(78),
    [anon_sym_null] = ACTIONS(78),
    [anon_sym_bool] = ACTIONS(78),
    [anon_sym_int] = ACTIONS(78),
    [anon_sym_uint] = ACTIONS(78),
    [anon_sym_float] = ACTIONS(78),
    [anon_sym_str] = ACTIONS(78),
    [anon_sym_use] = ACTIONS(78),
    [aux_sym_import_token1] = ACTIONS(78),
    [anon_sym_fn] = ACTIONS(78),
    [sym_number] = ACTIONS(76),
    [anon_sym_DQUOTE] = ACTIONS(76),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(80),
    [anon_sym_if] = ACTIONS(82),
    [anon_sym_elif] = ACTIONS(82),
    [anon_sym_else] = ACTIONS(82),
    [anon_sym_for] = ACTIONS(82),
    [anon_sym_while] = ACTIONS(82),
    [anon_sym_return] = ACTIONS(82),
    [anon_sym_as] = ACTIONS(82),
    [sym_comment] = ACTIONS(80),
    [anon_sym_true] = ACTIONS(82),
    [anon_sym_false] = ACTIONS(82),
    [anon_sym_null] = ACTIONS(82),
    [anon_sym_bool] = ACTIONS(82),
    [anon_sym_int] = ACTIONS(82),
    [anon_sym_uint] = ACTIONS(82),
    [anon_sym_float] = ACTIONS(82),
    [anon_sym_str] = ACTIONS(82),
    [anon_sym_use] = ACTIONS(82),
    [aux_sym_import_token1] = ACTIONS(82),
    [anon_sym_fn] = ACTIONS(82),
    [sym_number] = ACTIONS(80),
    [anon_sym_DQUOTE] = ACTIONS(80),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(84),
    [anon_sym_if] = ACTIONS(86),
    [anon_sym_elif] = ACTIONS(86),
    [anon_sym_else] = ACTIONS(86),
    [anon_sym_for] = ACTIONS(86),
    [anon_sym_while] = ACTIONS(86),
    [anon_sym_return] = ACTIONS(86),
    [anon_sym_as] = ACTIONS(86),
    [sym_comment] = ACTIONS(84),
    [anon_sym_true] = ACTIONS(86),
    [anon_sym_false] = ACTIONS(86),
    [anon_sym_null] = ACTIONS(86),
    [anon_sym_bool] = ACTIONS(86),
    [anon_sym_int] = ACTIONS(86),
    [anon_sym_uint] = ACTIONS(86),
    [anon_sym_float] = ACTIONS(86),
    [anon_sym_str] = ACTIONS(86),
    [anon_sym_use] = ACTIONS(86),
    [aux_sym_import_token1] = ACTIONS(86),
    [anon_sym_fn] = ACTIONS(86),
    [sym_number] = ACTIONS(84),
    [anon_sym_DQUOTE] = ACTIONS(84),
  },
  [STATE(12)] = {
    [ts_builtin_sym_end] = ACTIONS(88),
    [anon_sym_if] = ACTIONS(90),
    [anon_sym_elif] = ACTIONS(90),
    [anon_sym_else] = ACTIONS(90),
    [anon_sym_for] = ACTIONS(90),
    [anon_sym_while] = ACTIONS(90),
    [anon_sym_return] = ACTIONS(90),
    [anon_sym_as] = ACTIONS(90),
    [sym_comment] = ACTIONS(88),
    [anon_sym_true] = ACTIONS(90),
    [anon_sym_false] = ACTIONS(90),
    [anon_sym_null] = ACTIONS(90),
    [anon_sym_bool] = ACTIONS(90),
    [anon_sym_int] = ACTIONS(90),
    [anon_sym_uint] = ACTIONS(90),
    [anon_sym_float] = ACTIONS(90),
    [anon_sym_str] = ACTIONS(90),
    [anon_sym_use] = ACTIONS(90),
    [aux_sym_import_token1] = ACTIONS(90),
    [anon_sym_fn] = ACTIONS(90),
    [sym_number] = ACTIONS(88),
    [anon_sym_DQUOTE] = ACTIONS(88),
  },
  [STATE(13)] = {
    [ts_builtin_sym_end] = ACTIONS(92),
    [anon_sym_if] = ACTIONS(94),
    [anon_sym_elif] = ACTIONS(94),
    [anon_sym_else] = ACTIONS(94),
    [anon_sym_for] = ACTIONS(94),
    [anon_sym_while] = ACTIONS(94),
    [anon_sym_return] = ACTIONS(94),
    [anon_sym_as] = ACTIONS(94),
    [sym_comment] = ACTIONS(92),
    [anon_sym_true] = ACTIONS(94),
    [anon_sym_false] = ACTIONS(94),
    [anon_sym_null] = ACTIONS(94),
    [anon_sym_bool] = ACTIONS(94),
    [anon_sym_int] = ACTIONS(94),
    [anon_sym_uint] = ACTIONS(94),
    [anon_sym_float] = ACTIONS(94),
    [anon_sym_str] = ACTIONS(94),
    [anon_sym_use] = ACTIONS(94),
    [aux_sym_import_token1] = ACTIONS(94),
    [anon_sym_fn] = ACTIONS(94),
    [sym_number] = ACTIONS(92),
    [anon_sym_DQUOTE] = ACTIONS(92),
  },
  [STATE(14)] = {
    [ts_builtin_sym_end] = ACTIONS(96),
    [anon_sym_if] = ACTIONS(98),
    [anon_sym_elif] = ACTIONS(98),
    [anon_sym_else] = ACTIONS(98),
    [anon_sym_for] = ACTIONS(98),
    [anon_sym_while] = ACTIONS(98),
    [anon_sym_return] = ACTIONS(98),
    [anon_sym_as] = ACTIONS(98),
    [sym_comment] = ACTIONS(96),
    [anon_sym_true] = ACTIONS(98),
    [anon_sym_false] = ACTIONS(98),
    [anon_sym_null] = ACTIONS(98),
    [anon_sym_bool] = ACTIONS(98),
    [anon_sym_int] = ACTIONS(98),
    [anon_sym_uint] = ACTIONS(98),
    [anon_sym_float] = ACTIONS(98),
    [anon_sym_str] = ACTIONS(98),
    [anon_sym_use] = ACTIONS(98),
    [aux_sym_import_token1] = ACTIONS(98),
    [anon_sym_fn] = ACTIONS(98),
    [sym_number] = ACTIONS(96),
    [anon_sym_DQUOTE] = ACTIONS(96),
  },
  [STATE(15)] = {
    [ts_builtin_sym_end] = ACTIONS(100),
    [anon_sym_if] = ACTIONS(102),
    [anon_sym_elif] = ACTIONS(102),
    [anon_sym_else] = ACTIONS(102),
    [anon_sym_for] = ACTIONS(102),
    [anon_sym_while] = ACTIONS(102),
    [anon_sym_return] = ACTIONS(102),
    [anon_sym_as] = ACTIONS(102),
    [sym_comment] = ACTIONS(100),
    [anon_sym_true] = ACTIONS(102),
    [anon_sym_false] = ACTIONS(102),
    [anon_sym_null] = ACTIONS(102),
    [anon_sym_bool] = ACTIONS(102),
    [anon_sym_int] = ACTIONS(102),
    [anon_sym_uint] = ACTIONS(102),
    [anon_sym_float] = ACTIONS(102),
    [anon_sym_str] = ACTIONS(102),
    [anon_sym_use] = ACTIONS(102),
    [aux_sym_import_token1] = ACTIONS(102),
    [anon_sym_fn] = ACTIONS(102),
    [sym_number] = ACTIONS(100),
    [anon_sym_DQUOTE] = ACTIONS(100),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(104), 1,
      anon_sym_DQUOTE,
    ACTIONS(106), 1,
      aux_sym_string_token1,
    ACTIONS(108), 1,
      sym_escape,
    STATE(18), 1,
      aux_sym_string_repeat1,
  [13] = 4,
    ACTIONS(110), 1,
      anon_sym_DQUOTE,
    ACTIONS(112), 1,
      aux_sym_string_token1,
    ACTIONS(115), 1,
      sym_escape,
    STATE(17), 1,
      aux_sym_string_repeat1,
  [26] = 4,
    ACTIONS(118), 1,
      anon_sym_DQUOTE,
    ACTIONS(120), 1,
      aux_sym_string_token1,
    ACTIONS(122), 1,
      sym_escape,
    STATE(17), 1,
      aux_sym_string_repeat1,
  [39] = 3,
    ACTIONS(124), 1,
      aux_sym_import_token1,
    ACTIONS(126), 1,
      anon_sym_RPAREN,
    STATE(20), 1,
      sym_identifier,
  [49] = 3,
    ACTIONS(128), 1,
      anon_sym_COMMA,
    ACTIONS(130), 1,
      anon_sym_RPAREN,
    STATE(21), 1,
      aux_sym_parameter_list_repeat1,
  [59] = 3,
    ACTIONS(128), 1,
      anon_sym_COMMA,
    ACTIONS(132), 1,
      anon_sym_RPAREN,
    STATE(22), 1,
      aux_sym_parameter_list_repeat1,
  [69] = 3,
    ACTIONS(134), 1,
      anon_sym_COMMA,
    ACTIONS(137), 1,
      anon_sym_RPAREN,
    STATE(22), 1,
      aux_sym_parameter_list_repeat1,
  [79] = 2,
    ACTIONS(124), 1,
      aux_sym_import_token1,
    STATE(24), 1,
      sym_identifier,
  [86] = 2,
    ACTIONS(139), 1,
      anon_sym_LPAREN,
    STATE(13), 1,
      sym_parameter_list,
  [93] = 2,
    ACTIONS(124), 1,
      aux_sym_import_token1,
    STATE(26), 1,
      sym_identifier,
  [100] = 1,
    ACTIONS(137), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [105] = 1,
    ACTIONS(141), 1,
      aux_sym_import_token1,
  [109] = 1,
    ACTIONS(143), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(16)] = 0,
  [SMALL_STATE(17)] = 13,
  [SMALL_STATE(18)] = 26,
  [SMALL_STATE(19)] = 39,
  [SMALL_STATE(20)] = 49,
  [SMALL_STATE(21)] = 59,
  [SMALL_STATE(22)] = 69,
  [SMALL_STATE(23)] = 79,
  [SMALL_STATE(24)] = 86,
  [SMALL_STATE(25)] = 93,
  [SMALL_STATE(26)] = 100,
  [SMALL_STATE(27)] = 105,
  [SMALL_STATE(28)] = 109,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 2, 0, 1),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 2, 0, 1),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constant, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_special_type, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_special_type, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 3, 0, 2),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 3, 0, 2),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 4, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 4, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [115] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [118] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [134] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [143] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gscript(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "gscript",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
