/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 30
#define LARGE_STATE_COUNT 17
#define SYMBOL_COUNT 54
#define ALIAS_COUNT 2
#define TOKEN_COUNT 38
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_if = 1,
  anon_sym_elif = 2,
  anon_sym_else = 3,
  anon_sym_for = 4,
  anon_sym_while = 5,
  anon_sym_return = 6,
  anon_sym_as = 7,
  anon_sym_decl = 8,
  anon_sym_end = 9,
  anon_sym_done = 10,
  sym_comment = 11,
  anon_sym_true = 12,
  anon_sym_false = 13,
  anon_sym_null = 14,
  anon_sym_bool = 15,
  anon_sym_int = 16,
  anon_sym_uint = 17,
  anon_sym_float = 18,
  anon_sym_str = 19,
  anon_sym_use = 20,
  aux_sym_import_token1 = 21,
  anon_sym_fn = 22,
  anon_sym_LPAREN = 23,
  anon_sym_COMMA = 24,
  anon_sym_RPAREN = 25,
  anon_sym_EQ_EQ = 26,
  anon_sym_BANG_EQ = 27,
  anon_sym_EQ = 28,
  anon_sym_PLUS = 29,
  anon_sym_DASH = 30,
  anon_sym_SLASH = 31,
  anon_sym_STAR = 32,
  anon_sym_BANG = 33,
  sym_number = 34,
  anon_sym_DQUOTE = 35,
  aux_sym_string_token1 = 36,
  sym_escape = 37,
  sym_source_file = 38,
  sym__definition = 39,
  sym__expression = 40,
  sym_keyword = 41,
  sym_constant = 42,
  sym_type = 43,
  sym_special_type = 44,
  sym_import = 45,
  sym_function_definition = 46,
  sym_parameter_list = 47,
  sym_operator = 48,
  sym_string = 49,
  sym_identifier = 50,
  aux_sym_source_file_repeat1 = 51,
  aux_sym_parameter_list_repeat1 = 52,
  aux_sym_string_repeat1 = 53,
  alias_sym_function_name = 54,
  alias_sym_module_name = 55,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_if] = "if",
  [anon_sym_elif] = "elif",
  [anon_sym_else] = "else",
  [anon_sym_for] = "for",
  [anon_sym_while] = "while",
  [anon_sym_return] = "return",
  [anon_sym_as] = "as",
  [anon_sym_decl] = "decl",
  [anon_sym_end] = "end",
  [anon_sym_done] = "done",
  [sym_comment] = "comment",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_null] = "null",
  [anon_sym_bool] = "bool",
  [anon_sym_int] = "int",
  [anon_sym_uint] = "uint",
  [anon_sym_float] = "float",
  [anon_sym_str] = "str",
  [anon_sym_use] = "use",
  [aux_sym_import_token1] = "import_token1",
  [anon_sym_fn] = "fn",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_EQ] = "=",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_SLASH] = "/",
  [anon_sym_STAR] = "*",
  [anon_sym_BANG] = "!",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_escape] = "escape",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym__expression] = "_expression",
  [sym_keyword] = "keyword",
  [sym_constant] = "constant",
  [sym_type] = "type",
  [sym_special_type] = "special_type",
  [sym_import] = "import",
  [sym_function_definition] = "function_definition",
  [sym_parameter_list] = "parameter_list",
  [sym_operator] = "operator",
  [sym_string] = "string",
  [sym_identifier] = "identifier",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [alias_sym_function_name] = "function_name",
  [alias_sym_module_name] = "module_name",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_elif] = anon_sym_elif,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_decl] = anon_sym_decl,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_done] = anon_sym_done,
  [sym_comment] = sym_comment,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_null] = anon_sym_null,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_uint] = anon_sym_uint,
  [anon_sym_float] = anon_sym_float,
  [anon_sym_str] = anon_sym_str,
  [anon_sym_use] = anon_sym_use,
  [aux_sym_import_token1] = aux_sym_import_token1,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_BANG] = anon_sym_BANG,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_escape] = sym_escape,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym__expression] = sym__expression,
  [sym_keyword] = sym_keyword,
  [sym_constant] = sym_constant,
  [sym_type] = sym_type,
  [sym_special_type] = sym_special_type,
  [sym_import] = sym_import,
  [sym_function_definition] = sym_function_definition,
  [sym_parameter_list] = sym_parameter_list,
  [sym_operator] = sym_operator,
  [sym_string] = sym_string,
  [sym_identifier] = sym_identifier,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [alias_sym_function_name] = alias_sym_function_name,
  [alias_sym_module_name] = alias_sym_module_name,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_decl] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_done] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_null] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_uint] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_float] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_str] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_use] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_import_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_constant] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_special_type] = {
    .visible = true,
    .named = true,
  },
  [sym_import] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_function_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_module_name] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = alias_sym_module_name,
  },
  [2] = {
    [1] = alias_sym_function_name,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym_identifier, 2,
    sym_identifier,
    alias_sym_function_name,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      ADVANCE_MAP(
        '!', 83,
        '"', 86,
        '#', 16,
        '(', 73,
        ')', 75,
        '*', 82,
        '+', 79,
        ',', 74,
        '-', 80,
        '/', 81,
        '=', 78,
        '\\', 3,
        'a', 61,
        'b', 55,
        'd', 30,
        'e', 48,
        'f', 26,
        'i', 38,
        'n', 68,
        'r', 37,
        's', 67,
        't', 59,
        'u', 42,
        'w', 40,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('c' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '"') ADVANCE(86);
      if (lookahead == '\\') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(88);
      if (lookahead != 0) ADVANCE(87);
      END_STATE();
    case 2:
      if (lookahead == ')') ADVANCE(75);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 3:
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(89);
      END_STATE();
    case 4:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(85);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_elif);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_else);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_for);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_while);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_return);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_as);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_decl);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_end);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_done);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_null);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_bool);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_int);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_uint);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_float);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_str);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_use);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'a') ADVANCE(47);
      if (lookahead == 'l') ADVANCE(54);
      if (lookahead == 'n') ADVANCE(72);
      if (lookahead == 'o') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'a') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'c') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'd') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'e') ADVANCE(28);
      if (lookahead == 'o') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'e') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'e') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'e') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'e') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'e') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'e') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'e') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'f') ADVANCE(6);
      if (lookahead == 'n') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'f') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'h') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'i') ADVANCE(39);
      if (lookahead == 's') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'i') ADVANCE(53);
      if (lookahead == 's') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'i') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'l') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'l') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'l') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'l') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'l') ADVANCE(41);
      if (lookahead == 'n') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'l') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'l') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'n') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'n') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'n') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'o') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'o') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'o') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'r') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'r') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'r') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'r') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 's') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 's') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 't') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 't') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 't') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 't') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 't') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'u') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'u') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == 'u') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_fn);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(76);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(77);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(85);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(88);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(87);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_escape);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_elif] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_decl] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_done] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_null] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_uint] = ACTIONS(1),
    [anon_sym_float] = ACTIONS(1),
    [anon_sym_str] = ACTIONS(1),
    [anon_sym_use] = ACTIONS(1),
    [aux_sym_import_token1] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(29),
    [sym__definition] = STATE(2),
    [sym__expression] = STATE(2),
    [sym_keyword] = STATE(2),
    [sym_constant] = STATE(2),
    [sym_type] = STATE(2),
    [sym_special_type] = STATE(2),
    [sym_import] = STATE(2),
    [sym_function_definition] = STATE(2),
    [sym_operator] = STATE(2),
    [sym_string] = STATE(2),
    [sym_identifier] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_if] = ACTIONS(5),
    [anon_sym_elif] = ACTIONS(5),
    [anon_sym_else] = ACTIONS(5),
    [anon_sym_for] = ACTIONS(5),
    [anon_sym_while] = ACTIONS(5),
    [anon_sym_return] = ACTIONS(5),
    [anon_sym_as] = ACTIONS(5),
    [anon_sym_decl] = ACTIONS(5),
    [anon_sym_end] = ACTIONS(5),
    [anon_sym_done] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
    [anon_sym_true] = ACTIONS(9),
    [anon_sym_false] = ACTIONS(9),
    [anon_sym_null] = ACTIONS(9),
    [anon_sym_bool] = ACTIONS(11),
    [anon_sym_int] = ACTIONS(11),
    [anon_sym_uint] = ACTIONS(11),
    [anon_sym_float] = ACTIONS(11),
    [anon_sym_str] = ACTIONS(13),
    [anon_sym_use] = ACTIONS(15),
    [aux_sym_import_token1] = ACTIONS(17),
    [anon_sym_fn] = ACTIONS(19),
    [anon_sym_EQ_EQ] = ACTIONS(21),
    [anon_sym_BANG_EQ] = ACTIONS(21),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_SLASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(21),
    [anon_sym_BANG] = ACTIONS(23),
    [sym_number] = ACTIONS(7),
    [anon_sym_DQUOTE] = ACTIONS(25),
  },
  [STATE(2)] = {
    [sym__definition] = STATE(3),
    [sym__expression] = STATE(3),
    [sym_keyword] = STATE(3),
    [sym_constant] = STATE(3),
    [sym_type] = STATE(3),
    [sym_special_type] = STATE(3),
    [sym_import] = STATE(3),
    [sym_function_definition] = STATE(3),
    [sym_operator] = STATE(3),
    [sym_string] = STATE(3),
    [sym_identifier] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(27),
    [anon_sym_if] = ACTIONS(5),
    [anon_sym_elif] = ACTIONS(5),
    [anon_sym_else] = ACTIONS(5),
    [anon_sym_for] = ACTIONS(5),
    [anon_sym_while] = ACTIONS(5),
    [anon_sym_return] = ACTIONS(5),
    [anon_sym_as] = ACTIONS(5),
    [anon_sym_decl] = ACTIONS(5),
    [anon_sym_end] = ACTIONS(5),
    [anon_sym_done] = ACTIONS(5),
    [sym_comment] = ACTIONS(29),
    [anon_sym_true] = ACTIONS(9),
    [anon_sym_false] = ACTIONS(9),
    [anon_sym_null] = ACTIONS(9),
    [anon_sym_bool] = ACTIONS(11),
    [anon_sym_int] = ACTIONS(11),
    [anon_sym_uint] = ACTIONS(11),
    [anon_sym_float] = ACTIONS(11),
    [anon_sym_str] = ACTIONS(13),
    [anon_sym_use] = ACTIONS(15),
    [aux_sym_import_token1] = ACTIONS(17),
    [anon_sym_fn] = ACTIONS(19),
    [anon_sym_EQ_EQ] = ACTIONS(21),
    [anon_sym_BANG_EQ] = ACTIONS(21),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_SLASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(21),
    [anon_sym_BANG] = ACTIONS(23),
    [sym_number] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(25),
  },
  [STATE(3)] = {
    [sym__definition] = STATE(3),
    [sym__expression] = STATE(3),
    [sym_keyword] = STATE(3),
    [sym_constant] = STATE(3),
    [sym_type] = STATE(3),
    [sym_special_type] = STATE(3),
    [sym_import] = STATE(3),
    [sym_function_definition] = STATE(3),
    [sym_operator] = STATE(3),
    [sym_string] = STATE(3),
    [sym_identifier] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(31),
    [anon_sym_if] = ACTIONS(33),
    [anon_sym_elif] = ACTIONS(33),
    [anon_sym_else] = ACTIONS(33),
    [anon_sym_for] = ACTIONS(33),
    [anon_sym_while] = ACTIONS(33),
    [anon_sym_return] = ACTIONS(33),
    [anon_sym_as] = ACTIONS(33),
    [anon_sym_decl] = ACTIONS(33),
    [anon_sym_end] = ACTIONS(33),
    [anon_sym_done] = ACTIONS(33),
    [sym_comment] = ACTIONS(36),
    [anon_sym_true] = ACTIONS(39),
    [anon_sym_false] = ACTIONS(39),
    [anon_sym_null] = ACTIONS(39),
    [anon_sym_bool] = ACTIONS(42),
    [anon_sym_int] = ACTIONS(42),
    [anon_sym_uint] = ACTIONS(42),
    [anon_sym_float] = ACTIONS(42),
    [anon_sym_str] = ACTIONS(45),
    [anon_sym_use] = ACTIONS(48),
    [aux_sym_import_token1] = ACTIONS(51),
    [anon_sym_fn] = ACTIONS(54),
    [anon_sym_EQ_EQ] = ACTIONS(57),
    [anon_sym_BANG_EQ] = ACTIONS(57),
    [anon_sym_EQ] = ACTIONS(60),
    [anon_sym_PLUS] = ACTIONS(57),
    [anon_sym_DASH] = ACTIONS(57),
    [anon_sym_SLASH] = ACTIONS(57),
    [anon_sym_STAR] = ACTIONS(57),
    [anon_sym_BANG] = ACTIONS(60),
    [sym_number] = ACTIONS(36),
    [anon_sym_DQUOTE] = ACTIONS(63),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(66),
    [anon_sym_if] = ACTIONS(68),
    [anon_sym_elif] = ACTIONS(68),
    [anon_sym_else] = ACTIONS(68),
    [anon_sym_for] = ACTIONS(68),
    [anon_sym_while] = ACTIONS(68),
    [anon_sym_return] = ACTIONS(68),
    [anon_sym_as] = ACTIONS(68),
    [anon_sym_decl] = ACTIONS(68),
    [anon_sym_end] = ACTIONS(68),
    [anon_sym_done] = ACTIONS(68),
    [sym_comment] = ACTIONS(66),
    [anon_sym_true] = ACTIONS(68),
    [anon_sym_false] = ACTIONS(68),
    [anon_sym_null] = ACTIONS(68),
    [anon_sym_bool] = ACTIONS(68),
    [anon_sym_int] = ACTIONS(68),
    [anon_sym_uint] = ACTIONS(68),
    [anon_sym_float] = ACTIONS(68),
    [anon_sym_str] = ACTIONS(68),
    [anon_sym_use] = ACTIONS(68),
    [aux_sym_import_token1] = ACTIONS(68),
    [anon_sym_fn] = ACTIONS(68),
    [anon_sym_LPAREN] = ACTIONS(66),
    [anon_sym_COMMA] = ACTIONS(66),
    [anon_sym_RPAREN] = ACTIONS(66),
    [anon_sym_EQ_EQ] = ACTIONS(66),
    [anon_sym_BANG_EQ] = ACTIONS(66),
    [anon_sym_EQ] = ACTIONS(68),
    [anon_sym_PLUS] = ACTIONS(66),
    [anon_sym_DASH] = ACTIONS(66),
    [anon_sym_SLASH] = ACTIONS(66),
    [anon_sym_STAR] = ACTIONS(66),
    [anon_sym_BANG] = ACTIONS(68),
    [sym_number] = ACTIONS(66),
    [anon_sym_DQUOTE] = ACTIONS(66),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(70),
    [anon_sym_if] = ACTIONS(72),
    [anon_sym_elif] = ACTIONS(72),
    [anon_sym_else] = ACTIONS(72),
    [anon_sym_for] = ACTIONS(72),
    [anon_sym_while] = ACTIONS(72),
    [anon_sym_return] = ACTIONS(72),
    [anon_sym_as] = ACTIONS(72),
    [anon_sym_decl] = ACTIONS(72),
    [anon_sym_end] = ACTIONS(72),
    [anon_sym_done] = ACTIONS(72),
    [sym_comment] = ACTIONS(70),
    [anon_sym_true] = ACTIONS(72),
    [anon_sym_false] = ACTIONS(72),
    [anon_sym_null] = ACTIONS(72),
    [anon_sym_bool] = ACTIONS(72),
    [anon_sym_int] = ACTIONS(72),
    [anon_sym_uint] = ACTIONS(72),
    [anon_sym_float] = ACTIONS(72),
    [anon_sym_str] = ACTIONS(72),
    [anon_sym_use] = ACTIONS(72),
    [aux_sym_import_token1] = ACTIONS(72),
    [anon_sym_fn] = ACTIONS(72),
    [anon_sym_EQ_EQ] = ACTIONS(70),
    [anon_sym_BANG_EQ] = ACTIONS(70),
    [anon_sym_EQ] = ACTIONS(72),
    [anon_sym_PLUS] = ACTIONS(70),
    [anon_sym_DASH] = ACTIONS(70),
    [anon_sym_SLASH] = ACTIONS(70),
    [anon_sym_STAR] = ACTIONS(70),
    [anon_sym_BANG] = ACTIONS(72),
    [sym_number] = ACTIONS(70),
    [anon_sym_DQUOTE] = ACTIONS(70),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(74),
    [anon_sym_if] = ACTIONS(76),
    [anon_sym_elif] = ACTIONS(76),
    [anon_sym_else] = ACTIONS(76),
    [anon_sym_for] = ACTIONS(76),
    [anon_sym_while] = ACTIONS(76),
    [anon_sym_return] = ACTIONS(76),
    [anon_sym_as] = ACTIONS(76),
    [anon_sym_decl] = ACTIONS(76),
    [anon_sym_end] = ACTIONS(76),
    [anon_sym_done] = ACTIONS(76),
    [sym_comment] = ACTIONS(74),
    [anon_sym_true] = ACTIONS(76),
    [anon_sym_false] = ACTIONS(76),
    [anon_sym_null] = ACTIONS(76),
    [anon_sym_bool] = ACTIONS(76),
    [anon_sym_int] = ACTIONS(76),
    [anon_sym_uint] = ACTIONS(76),
    [anon_sym_float] = ACTIONS(76),
    [anon_sym_str] = ACTIONS(76),
    [anon_sym_use] = ACTIONS(76),
    [aux_sym_import_token1] = ACTIONS(76),
    [anon_sym_fn] = ACTIONS(76),
    [anon_sym_EQ_EQ] = ACTIONS(74),
    [anon_sym_BANG_EQ] = ACTIONS(74),
    [anon_sym_EQ] = ACTIONS(76),
    [anon_sym_PLUS] = ACTIONS(74),
    [anon_sym_DASH] = ACTIONS(74),
    [anon_sym_SLASH] = ACTIONS(74),
    [anon_sym_STAR] = ACTIONS(74),
    [anon_sym_BANG] = ACTIONS(76),
    [sym_number] = ACTIONS(74),
    [anon_sym_DQUOTE] = ACTIONS(74),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(78),
    [anon_sym_if] = ACTIONS(80),
    [anon_sym_elif] = ACTIONS(80),
    [anon_sym_else] = ACTIONS(80),
    [anon_sym_for] = ACTIONS(80),
    [anon_sym_while] = ACTIONS(80),
    [anon_sym_return] = ACTIONS(80),
    [anon_sym_as] = ACTIONS(80),
    [anon_sym_decl] = ACTIONS(80),
    [anon_sym_end] = ACTIONS(80),
    [anon_sym_done] = ACTIONS(80),
    [sym_comment] = ACTIONS(78),
    [anon_sym_true] = ACTIONS(80),
    [anon_sym_false] = ACTIONS(80),
    [anon_sym_null] = ACTIONS(80),
    [anon_sym_bool] = ACTIONS(80),
    [anon_sym_int] = ACTIONS(80),
    [anon_sym_uint] = ACTIONS(80),
    [anon_sym_float] = ACTIONS(80),
    [anon_sym_str] = ACTIONS(80),
    [anon_sym_use] = ACTIONS(80),
    [aux_sym_import_token1] = ACTIONS(80),
    [anon_sym_fn] = ACTIONS(80),
    [anon_sym_EQ_EQ] = ACTIONS(78),
    [anon_sym_BANG_EQ] = ACTIONS(78),
    [anon_sym_EQ] = ACTIONS(80),
    [anon_sym_PLUS] = ACTIONS(78),
    [anon_sym_DASH] = ACTIONS(78),
    [anon_sym_SLASH] = ACTIONS(78),
    [anon_sym_STAR] = ACTIONS(78),
    [anon_sym_BANG] = ACTIONS(80),
    [sym_number] = ACTIONS(78),
    [anon_sym_DQUOTE] = ACTIONS(78),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(82),
    [anon_sym_if] = ACTIONS(84),
    [anon_sym_elif] = ACTIONS(84),
    [anon_sym_else] = ACTIONS(84),
    [anon_sym_for] = ACTIONS(84),
    [anon_sym_while] = ACTIONS(84),
    [anon_sym_return] = ACTIONS(84),
    [anon_sym_as] = ACTIONS(84),
    [anon_sym_decl] = ACTIONS(84),
    [anon_sym_end] = ACTIONS(84),
    [anon_sym_done] = ACTIONS(84),
    [sym_comment] = ACTIONS(82),
    [anon_sym_true] = ACTIONS(84),
    [anon_sym_false] = ACTIONS(84),
    [anon_sym_null] = ACTIONS(84),
    [anon_sym_bool] = ACTIONS(84),
    [anon_sym_int] = ACTIONS(84),
    [anon_sym_uint] = ACTIONS(84),
    [anon_sym_float] = ACTIONS(84),
    [anon_sym_str] = ACTIONS(84),
    [anon_sym_use] = ACTIONS(84),
    [aux_sym_import_token1] = ACTIONS(84),
    [anon_sym_fn] = ACTIONS(84),
    [anon_sym_EQ_EQ] = ACTIONS(82),
    [anon_sym_BANG_EQ] = ACTIONS(82),
    [anon_sym_EQ] = ACTIONS(84),
    [anon_sym_PLUS] = ACTIONS(82),
    [anon_sym_DASH] = ACTIONS(82),
    [anon_sym_SLASH] = ACTIONS(82),
    [anon_sym_STAR] = ACTIONS(82),
    [anon_sym_BANG] = ACTIONS(84),
    [sym_number] = ACTIONS(82),
    [anon_sym_DQUOTE] = ACTIONS(82),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(86),
    [anon_sym_if] = ACTIONS(88),
    [anon_sym_elif] = ACTIONS(88),
    [anon_sym_else] = ACTIONS(88),
    [anon_sym_for] = ACTIONS(88),
    [anon_sym_while] = ACTIONS(88),
    [anon_sym_return] = ACTIONS(88),
    [anon_sym_as] = ACTIONS(88),
    [anon_sym_decl] = ACTIONS(88),
    [anon_sym_end] = ACTIONS(88),
    [anon_sym_done] = ACTIONS(88),
    [sym_comment] = ACTIONS(86),
    [anon_sym_true] = ACTIONS(88),
    [anon_sym_false] = ACTIONS(88),
    [anon_sym_null] = ACTIONS(88),
    [anon_sym_bool] = ACTIONS(88),
    [anon_sym_int] = ACTIONS(88),
    [anon_sym_uint] = ACTIONS(88),
    [anon_sym_float] = ACTIONS(88),
    [anon_sym_str] = ACTIONS(88),
    [anon_sym_use] = ACTIONS(88),
    [aux_sym_import_token1] = ACTIONS(88),
    [anon_sym_fn] = ACTIONS(88),
    [anon_sym_EQ_EQ] = ACTIONS(86),
    [anon_sym_BANG_EQ] = ACTIONS(86),
    [anon_sym_EQ] = ACTIONS(88),
    [anon_sym_PLUS] = ACTIONS(86),
    [anon_sym_DASH] = ACTIONS(86),
    [anon_sym_SLASH] = ACTIONS(86),
    [anon_sym_STAR] = ACTIONS(86),
    [anon_sym_BANG] = ACTIONS(88),
    [sym_number] = ACTIONS(86),
    [anon_sym_DQUOTE] = ACTIONS(86),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(90),
    [anon_sym_if] = ACTIONS(92),
    [anon_sym_elif] = ACTIONS(92),
    [anon_sym_else] = ACTIONS(92),
    [anon_sym_for] = ACTIONS(92),
    [anon_sym_while] = ACTIONS(92),
    [anon_sym_return] = ACTIONS(92),
    [anon_sym_as] = ACTIONS(92),
    [anon_sym_decl] = ACTIONS(92),
    [anon_sym_end] = ACTIONS(92),
    [anon_sym_done] = ACTIONS(92),
    [sym_comment] = ACTIONS(90),
    [anon_sym_true] = ACTIONS(92),
    [anon_sym_false] = ACTIONS(92),
    [anon_sym_null] = ACTIONS(92),
    [anon_sym_bool] = ACTIONS(92),
    [anon_sym_int] = ACTIONS(92),
    [anon_sym_uint] = ACTIONS(92),
    [anon_sym_float] = ACTIONS(92),
    [anon_sym_str] = ACTIONS(92),
    [anon_sym_use] = ACTIONS(92),
    [aux_sym_import_token1] = ACTIONS(92),
    [anon_sym_fn] = ACTIONS(92),
    [anon_sym_EQ_EQ] = ACTIONS(90),
    [anon_sym_BANG_EQ] = ACTIONS(90),
    [anon_sym_EQ] = ACTIONS(92),
    [anon_sym_PLUS] = ACTIONS(90),
    [anon_sym_DASH] = ACTIONS(90),
    [anon_sym_SLASH] = ACTIONS(90),
    [anon_sym_STAR] = ACTIONS(90),
    [anon_sym_BANG] = ACTIONS(92),
    [sym_number] = ACTIONS(90),
    [anon_sym_DQUOTE] = ACTIONS(90),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(94),
    [anon_sym_if] = ACTIONS(96),
    [anon_sym_elif] = ACTIONS(96),
    [anon_sym_else] = ACTIONS(96),
    [anon_sym_for] = ACTIONS(96),
    [anon_sym_while] = ACTIONS(96),
    [anon_sym_return] = ACTIONS(96),
    [anon_sym_as] = ACTIONS(96),
    [anon_sym_decl] = ACTIONS(96),
    [anon_sym_end] = ACTIONS(96),
    [anon_sym_done] = ACTIONS(96),
    [sym_comment] = ACTIONS(94),
    [anon_sym_true] = ACTIONS(96),
    [anon_sym_false] = ACTIONS(96),
    [anon_sym_null] = ACTIONS(96),
    [anon_sym_bool] = ACTIONS(96),
    [anon_sym_int] = ACTIONS(96),
    [anon_sym_uint] = ACTIONS(96),
    [anon_sym_float] = ACTIONS(96),
    [anon_sym_str] = ACTIONS(96),
    [anon_sym_use] = ACTIONS(96),
    [aux_sym_import_token1] = ACTIONS(96),
    [anon_sym_fn] = ACTIONS(96),
    [anon_sym_EQ_EQ] = ACTIONS(94),
    [anon_sym_BANG_EQ] = ACTIONS(94),
    [anon_sym_EQ] = ACTIONS(96),
    [anon_sym_PLUS] = ACTIONS(94),
    [anon_sym_DASH] = ACTIONS(94),
    [anon_sym_SLASH] = ACTIONS(94),
    [anon_sym_STAR] = ACTIONS(94),
    [anon_sym_BANG] = ACTIONS(96),
    [sym_number] = ACTIONS(94),
    [anon_sym_DQUOTE] = ACTIONS(94),
  },
  [STATE(12)] = {
    [ts_builtin_sym_end] = ACTIONS(98),
    [anon_sym_if] = ACTIONS(100),
    [anon_sym_elif] = ACTIONS(100),
    [anon_sym_else] = ACTIONS(100),
    [anon_sym_for] = ACTIONS(100),
    [anon_sym_while] = ACTIONS(100),
    [anon_sym_return] = ACTIONS(100),
    [anon_sym_as] = ACTIONS(100),
    [anon_sym_decl] = ACTIONS(100),
    [anon_sym_end] = ACTIONS(100),
    [anon_sym_done] = ACTIONS(100),
    [sym_comment] = ACTIONS(98),
    [anon_sym_true] = ACTIONS(100),
    [anon_sym_false] = ACTIONS(100),
    [anon_sym_null] = ACTIONS(100),
    [anon_sym_bool] = ACTIONS(100),
    [anon_sym_int] = ACTIONS(100),
    [anon_sym_uint] = ACTIONS(100),
    [anon_sym_float] = ACTIONS(100),
    [anon_sym_str] = ACTIONS(100),
    [anon_sym_use] = ACTIONS(100),
    [aux_sym_import_token1] = ACTIONS(100),
    [anon_sym_fn] = ACTIONS(100),
    [anon_sym_EQ_EQ] = ACTIONS(98),
    [anon_sym_BANG_EQ] = ACTIONS(98),
    [anon_sym_EQ] = ACTIONS(100),
    [anon_sym_PLUS] = ACTIONS(98),
    [anon_sym_DASH] = ACTIONS(98),
    [anon_sym_SLASH] = ACTIONS(98),
    [anon_sym_STAR] = ACTIONS(98),
    [anon_sym_BANG] = ACTIONS(100),
    [sym_number] = ACTIONS(98),
    [anon_sym_DQUOTE] = ACTIONS(98),
  },
  [STATE(13)] = {
    [ts_builtin_sym_end] = ACTIONS(102),
    [anon_sym_if] = ACTIONS(104),
    [anon_sym_elif] = ACTIONS(104),
    [anon_sym_else] = ACTIONS(104),
    [anon_sym_for] = ACTIONS(104),
    [anon_sym_while] = ACTIONS(104),
    [anon_sym_return] = ACTIONS(104),
    [anon_sym_as] = ACTIONS(104),
    [anon_sym_decl] = ACTIONS(104),
    [anon_sym_end] = ACTIONS(104),
    [anon_sym_done] = ACTIONS(104),
    [sym_comment] = ACTIONS(102),
    [anon_sym_true] = ACTIONS(104),
    [anon_sym_false] = ACTIONS(104),
    [anon_sym_null] = ACTIONS(104),
    [anon_sym_bool] = ACTIONS(104),
    [anon_sym_int] = ACTIONS(104),
    [anon_sym_uint] = ACTIONS(104),
    [anon_sym_float] = ACTIONS(104),
    [anon_sym_str] = ACTIONS(104),
    [anon_sym_use] = ACTIONS(104),
    [aux_sym_import_token1] = ACTIONS(104),
    [anon_sym_fn] = ACTIONS(104),
    [anon_sym_EQ_EQ] = ACTIONS(102),
    [anon_sym_BANG_EQ] = ACTIONS(102),
    [anon_sym_EQ] = ACTIONS(104),
    [anon_sym_PLUS] = ACTIONS(102),
    [anon_sym_DASH] = ACTIONS(102),
    [anon_sym_SLASH] = ACTIONS(102),
    [anon_sym_STAR] = ACTIONS(102),
    [anon_sym_BANG] = ACTIONS(104),
    [sym_number] = ACTIONS(102),
    [anon_sym_DQUOTE] = ACTIONS(102),
  },
  [STATE(14)] = {
    [ts_builtin_sym_end] = ACTIONS(106),
    [anon_sym_if] = ACTIONS(108),
    [anon_sym_elif] = ACTIONS(108),
    [anon_sym_else] = ACTIONS(108),
    [anon_sym_for] = ACTIONS(108),
    [anon_sym_while] = ACTIONS(108),
    [anon_sym_return] = ACTIONS(108),
    [anon_sym_as] = ACTIONS(108),
    [anon_sym_decl] = ACTIONS(108),
    [anon_sym_end] = ACTIONS(108),
    [anon_sym_done] = ACTIONS(108),
    [sym_comment] = ACTIONS(106),
    [anon_sym_true] = ACTIONS(108),
    [anon_sym_false] = ACTIONS(108),
    [anon_sym_null] = ACTIONS(108),
    [anon_sym_bool] = ACTIONS(108),
    [anon_sym_int] = ACTIONS(108),
    [anon_sym_uint] = ACTIONS(108),
    [anon_sym_float] = ACTIONS(108),
    [anon_sym_str] = ACTIONS(108),
    [anon_sym_use] = ACTIONS(108),
    [aux_sym_import_token1] = ACTIONS(108),
    [anon_sym_fn] = ACTIONS(108),
    [anon_sym_EQ_EQ] = ACTIONS(106),
    [anon_sym_BANG_EQ] = ACTIONS(106),
    [anon_sym_EQ] = ACTIONS(108),
    [anon_sym_PLUS] = ACTIONS(106),
    [anon_sym_DASH] = ACTIONS(106),
    [anon_sym_SLASH] = ACTIONS(106),
    [anon_sym_STAR] = ACTIONS(106),
    [anon_sym_BANG] = ACTIONS(108),
    [sym_number] = ACTIONS(106),
    [anon_sym_DQUOTE] = ACTIONS(106),
  },
  [STATE(15)] = {
    [ts_builtin_sym_end] = ACTIONS(110),
    [anon_sym_if] = ACTIONS(112),
    [anon_sym_elif] = ACTIONS(112),
    [anon_sym_else] = ACTIONS(112),
    [anon_sym_for] = ACTIONS(112),
    [anon_sym_while] = ACTIONS(112),
    [anon_sym_return] = ACTIONS(112),
    [anon_sym_as] = ACTIONS(112),
    [anon_sym_decl] = ACTIONS(112),
    [anon_sym_end] = ACTIONS(112),
    [anon_sym_done] = ACTIONS(112),
    [sym_comment] = ACTIONS(110),
    [anon_sym_true] = ACTIONS(112),
    [anon_sym_false] = ACTIONS(112),
    [anon_sym_null] = ACTIONS(112),
    [anon_sym_bool] = ACTIONS(112),
    [anon_sym_int] = ACTIONS(112),
    [anon_sym_uint] = ACTIONS(112),
    [anon_sym_float] = ACTIONS(112),
    [anon_sym_str] = ACTIONS(112),
    [anon_sym_use] = ACTIONS(112),
    [aux_sym_import_token1] = ACTIONS(112),
    [anon_sym_fn] = ACTIONS(112),
    [anon_sym_EQ_EQ] = ACTIONS(110),
    [anon_sym_BANG_EQ] = ACTIONS(110),
    [anon_sym_EQ] = ACTIONS(112),
    [anon_sym_PLUS] = ACTIONS(110),
    [anon_sym_DASH] = ACTIONS(110),
    [anon_sym_SLASH] = ACTIONS(110),
    [anon_sym_STAR] = ACTIONS(110),
    [anon_sym_BANG] = ACTIONS(112),
    [sym_number] = ACTIONS(110),
    [anon_sym_DQUOTE] = ACTIONS(110),
  },
  [STATE(16)] = {
    [ts_builtin_sym_end] = ACTIONS(114),
    [anon_sym_if] = ACTIONS(116),
    [anon_sym_elif] = ACTIONS(116),
    [anon_sym_else] = ACTIONS(116),
    [anon_sym_for] = ACTIONS(116),
    [anon_sym_while] = ACTIONS(116),
    [anon_sym_return] = ACTIONS(116),
    [anon_sym_as] = ACTIONS(116),
    [anon_sym_decl] = ACTIONS(116),
    [anon_sym_end] = ACTIONS(116),
    [anon_sym_done] = ACTIONS(116),
    [sym_comment] = ACTIONS(114),
    [anon_sym_true] = ACTIONS(116),
    [anon_sym_false] = ACTIONS(116),
    [anon_sym_null] = ACTIONS(116),
    [anon_sym_bool] = ACTIONS(116),
    [anon_sym_int] = ACTIONS(116),
    [anon_sym_uint] = ACTIONS(116),
    [anon_sym_float] = ACTIONS(116),
    [anon_sym_str] = ACTIONS(116),
    [anon_sym_use] = ACTIONS(116),
    [aux_sym_import_token1] = ACTIONS(116),
    [anon_sym_fn] = ACTIONS(116),
    [anon_sym_EQ_EQ] = ACTIONS(114),
    [anon_sym_BANG_EQ] = ACTIONS(114),
    [anon_sym_EQ] = ACTIONS(116),
    [anon_sym_PLUS] = ACTIONS(114),
    [anon_sym_DASH] = ACTIONS(114),
    [anon_sym_SLASH] = ACTIONS(114),
    [anon_sym_STAR] = ACTIONS(114),
    [anon_sym_BANG] = ACTIONS(116),
    [sym_number] = ACTIONS(114),
    [anon_sym_DQUOTE] = ACTIONS(114),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(118), 1,
      anon_sym_DQUOTE,
    ACTIONS(120), 1,
      aux_sym_string_token1,
    ACTIONS(122), 1,
      sym_escape,
    STATE(19), 1,
      aux_sym_string_repeat1,
  [13] = 4,
    ACTIONS(124), 1,
      anon_sym_DQUOTE,
    ACTIONS(126), 1,
      aux_sym_string_token1,
    ACTIONS(129), 1,
      sym_escape,
    STATE(18), 1,
      aux_sym_string_repeat1,
  [26] = 4,
    ACTIONS(132), 1,
      anon_sym_DQUOTE,
    ACTIONS(134), 1,
      aux_sym_string_token1,
    ACTIONS(136), 1,
      sym_escape,
    STATE(18), 1,
      aux_sym_string_repeat1,
  [39] = 3,
    ACTIONS(138), 1,
      aux_sym_import_token1,
    ACTIONS(140), 1,
      anon_sym_RPAREN,
    STATE(21), 1,
      sym_identifier,
  [49] = 3,
    ACTIONS(142), 1,
      anon_sym_COMMA,
    ACTIONS(144), 1,
      anon_sym_RPAREN,
    STATE(22), 1,
      aux_sym_parameter_list_repeat1,
  [59] = 3,
    ACTIONS(142), 1,
      anon_sym_COMMA,
    ACTIONS(146), 1,
      anon_sym_RPAREN,
    STATE(23), 1,
      aux_sym_parameter_list_repeat1,
  [69] = 3,
    ACTIONS(148), 1,
      anon_sym_COMMA,
    ACTIONS(151), 1,
      anon_sym_RPAREN,
    STATE(23), 1,
      aux_sym_parameter_list_repeat1,
  [79] = 2,
    ACTIONS(138), 1,
      aux_sym_import_token1,
    STATE(25), 1,
      sym_identifier,
  [86] = 2,
    ACTIONS(153), 1,
      anon_sym_LPAREN,
    STATE(14), 1,
      sym_parameter_list,
  [93] = 2,
    ACTIONS(138), 1,
      aux_sym_import_token1,
    STATE(27), 1,
      sym_identifier,
  [100] = 1,
    ACTIONS(151), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [105] = 1,
    ACTIONS(155), 1,
      aux_sym_import_token1,
  [109] = 1,
    ACTIONS(157), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(17)] = 0,
  [SMALL_STATE(18)] = 13,
  [SMALL_STATE(19)] = 26,
  [SMALL_STATE(20)] = 39,
  [SMALL_STATE(21)] = 49,
  [SMALL_STATE(22)] = 59,
  [SMALL_STATE(23)] = 69,
  [SMALL_STATE(24)] = 79,
  [SMALL_STATE(25)] = 86,
  [SMALL_STATE(26)] = 93,
  [SMALL_STATE(27)] = 100,
  [SMALL_STATE(28)] = 105,
  [SMALL_STATE(29)] = 109,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier, 1, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_special_type, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_special_type, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operator, 1, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constant, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword, 1, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword, 1, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 2, 0, 1),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 2, 0, 1),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 3, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 3, 0, 2),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 3, 0, 2),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 4, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 4, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [129] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [148] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [157] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gscript(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "gscript",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
